export const staticStyle = {
  letter: {
    position: "relative",
    margin: 0,
    padding: 0,
    border: 0,
    fontSize: 0,
    lineHeight: 0,
    boxSizing: "border-box",
    textAlign: "var(--align)",
    whiteSpace: "pre-wrap",
  },
  element: {
    position: "relative",
    display: "inline-block",
    margin: 0,
    padding: 0,
    border: 0,
    boxSizing: "border-box",
    whiteSpace: "pre",

    color: "var(--color)",
    fontSize: "var(--font-size)",
    fontFamily: "var(--font-family)",
    fontStyle: "var(--font-style)",
    fontVariant: "var(--font-variant)",
    fontWeight: "var(--font-weight)",
    lineHeight: "var(--height)",
    textAlign: "var(--align)",
  },
}